Add ModCore ( + TestBlock SPG-62)
freedom-mod-development-community/anti-raid-weapons pull request #3
Opened 2021-11-27 09:10 UTC by KumaYamamoto

2021-11-27 13:10 UTC, anatawa12 requested changes
私の感性なので、私がレビューした場所について、違うと思った場所があれば教えて下さい。
パッケージ構造とかdiscord上で既にごういがとれていたらすみません。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/ARWMod.kt
> +class ARWMod {
objectにして、`@JvmStatic`な`@Mod.InstanceFactory`でthisをreturnにしませんか？

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/ARWCreativeTab.kt
> +package xyz.fmdc.arw.modcore
modcoreっていうパッケージ名あまり良くないと思います。ARWCreativeTabはルートかなぁ...

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/KotlinUtil.kt
> +package xyz.fmdc.arw.modcore
同様にutilは`arw`package直下がいいと思います

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/PacketHandlerARW.kt
> +package xyz.fmdc.arw.modcore
パケット系は`network`とか`packets`に入れるのがそれなりに主流な気がします。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/WorldEventListener.kt
> +object WorldEventListener {
使っていないなら削除がいいと思います。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/message/TileEntityMessage.kt
> +package xyz.fmdc.arw.modcore.baseclass.message
`.network`以下かなぁ

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/TileCustomBase.kt
> +        return if (blockType is ModelNormalBlockContainer) {
ModelNormalBlockContainerを実装したものが絶対に使うTileEntityがあればそっちに移動したほうがいいかと。`ModelNormalModelBase`がそうだったりすると嬉しい。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/TileCustomBase.kt
> +open class TileCustomBase : TileEntity() {
これ、なくていいならないほうがいいと思います。`getDescriptionPacket`や`onDataPacket`は必要な各ブロックでkotlinUtilなりでかんたんに実装できるようにするのがいいと思います。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatableYaw.kt
> +interface IRotatableYaw {
pitchと同様に、`IYawRotatable` (pitch-rotatable, 「yawが回転可能な」という形容詞になるじゃず) のほうが自然だと思います。 rotatable yawだと回転可能なyaw(名詞)って意味になってしまうので。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    fun syncAngleSerToCli() {
syncAngleToClientがいいと思います。Server - Clientは原則そうなのでServerがいらないと思うのと、Ser/Cliという略し方は分かりづらいと思います

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +interface IRotatablePitch {
`IPitchRotatable` (pitch-rotatable, 「pitchが回転可能な」という形容詞になるはず) のほうが自然だと思います。 rotatable pitchだと回転可能なpitch(名詞)って意味になってしまうので。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
多分ですが、`pitchDeg by moduleRotatablePitch::pitchDeg`が使えるかと思います

ですがそれ以前に拡張プロパティのほうがいいと思います。`moduleRotatablePitch`との整合性を保つこと考えると。この２つの間で別の値が入り得るのはバグの要因だと思います

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +open class ModuleRotatablePitch {
DegかRadかどっちらか一方で保存して、もう片方は常に計算するようにしたいです。

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +    private var _pitchDeg: Double = 0.0
_pitchDegじゃなくても、`field`使えば実装できると思います。

参考：https://kotlinlang.org/docs/properties.html#backing-fields

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +open class ModuleRotatableYaw {
Pitchと同様

2021-11-27 13:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/registry/RegistryBlockAndTileEntity.kt
> +object RegistryBlockAndTileEntity {
AndTileEntityって単語いらないと私は思いますがどう思いますか？

2021-11-27 13:11 UTC, anatawa12 commented
また、Git(diff)の仕様上面倒事が起きることがあるため、それの回避のために、最終行に開業を入れるのをよろしくおねがいします。

2021-11-27 13:26 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/ARWMod.kt
> +class ARWMod {
instance　を
`
@Mod.InstanceFactory
    fun instance(): ARWMod {
        return this
    }
`
に置き換える感じ？

2021-11-27 13:34 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/registry/RegistryBlockAndTileEntity.kt
> +object RegistryBlockAndTileEntity {
いらないかなぁ。と思いつつ、とりまつけとくか。でつけたやつ。
消すか。

2021-11-27 13:36 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +open class ModuleRotatablePitch {
そのほうがいいか。

2021-11-27 13:48 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
クラスにほしい機能を難しいこと気にせずにたくさんの機能を持ったものをべたべたくっつけれるようにしつつ、tile.pitchDeg で取得できるようにしたいと思ってこういう実装にしてたんですよね。拡張プロパティだと`var ModuleRotatablePitch.pitchDeg` ?

2021-11-27 13:49 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/WorldEventListener.kt
> +object WorldEventListener {
必要になったタイミングで追加すればいいか。削除。

2021-11-27 13:53 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +    private var _pitchDeg: Double = 0.0
上の奴と合わせると `var pitchDeg: Double = 0.0` 単体になるなぁ。

2021-11-27 13:54 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/ARWCreativeTab.kt
> +package xyz.fmdc.arw.modcore
何かいい名前あります？

2021-11-28 01:18 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/ARWMod.kt
> +class ARWMod {
だいたいそういうことです。
staticなメソッドにしたいので`@JvmStatic`の付与を忘れないようお願いします。
また、見た目的には以下の形のほうがきれいかと思います
```
fun instance() = this
```

2021-11-28 01:18 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/ARWCreativeTab.kt
> +package xyz.fmdc.arw.modcore
このクラスに関してはarw直下がいいと思います

2021-11-28 01:19 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
IRotatablePitch.pitchDeg拡張プロパティを私は想定してます

2021-11-28 01:22 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/ARWCreativeTab.kt
> +package xyz.fmdc.arw.modcore
クラス単体のことか。

2021-11-28 01:23 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
なるほど。

2021-11-28 05:57 UTC, anatawa12 requested changes

2021-11-28 05:57 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/network/PacketHandlerARW.kt
> +
今気づいたので書きます。SyncAngleMessageのregister忘れてます

2021-11-28 05:57 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +package xyz.fmdc.arw.modcore
パッケージ名が変わってません

2021-11-28 07:42 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
拡張プロパティーを用いる場合、fieldがうまく使えず、classの中で拡張プロパティーをうまく宣言できないのでModuleは拡張プロパティーが置いてあるただのファイルになりそう。それなら、interfaceのほうにまとめちゃうか。

2021-11-28 08:13 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +package xyz.fmdc.arw.modcore
中身分類してあるし外出しちゃうか。

2021-11-28 08:48 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/network/PacketHandlerARW.kt
> +
忘れてますね。追加。

2021-11-28 23:29 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
Moduleの値を取得する拡張プロパティとして、

```
var IRotatablePitch.pitchDeg
    get() = moduleRotatablePitch.pitchDeg
    set(value) {
        moduleRotatablePitch.pitchDeg = value
    }
```
を想定してました

2021-11-29 11:20 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    var pitchDeg: Double
修正

2021-11-29 11:20 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +open class ModuleRotatablePitch {
Degに統一

2021-11-29 11:20 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +    private var _pitchDeg: Double = 0.0
拡張プロパティーに変更

2021-11-29 11:21 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +open class ModuleRotatableYaw {
変更

2021-11-29 12:10 UTC, anatawa12 requested changes

2021-11-29 12:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/IRotatableYaw.kt
> +}
new line at the end of the file

2021-11-29 12:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +    }
new line at the end of the file

2021-11-29 12:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +    }
new line at the end of the file

2021-11-29 12:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +var IRotatablePitch.pitchDeg: Double
IRotatablePitch.kt内にするべきだと思う

2021-11-29 12:10 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +var IRotatableYaw.yawDeg: Double
IRotatableYaw.kt内にするべきだと思う

2021-11-29 12:11 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +open class ModuleRotatablePitch {
計算するタイプの(拡張)プロパティを生やすってつもりだったんですけどなくしても問題ない感じですか？なくして問題ないならこのままResolveしてください。

2021-11-29 12:11 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +open class ModuleRotatableYaw {
Pitchと同様に問題ないならこのままResolveしてください。

2021-11-29 12:24 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +open class ModuleRotatablePitch {
あー。そのほうが便利。というか、最初からそのつもりでせっかく作ってたのに、消しちゃってたな。
対応。

2021-11-29 12:24 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +open class ModuleRotatableYaw {
対応

2021-11-29 12:24 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/IRotatableYaw.kt
> +}
あ”。
対応

2021-11-29 12:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +    }
あ”。
対応

2021-11-29 12:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +    }
あ”。
対応

2021-11-29 12:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatablePitch.kt
> +var IRotatablePitch.pitchDeg: Double
対応

2021-11-29 12:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/module/rotatable/ModuleRotatableYaw.kt
> +var IRotatableYaw.yawDeg: Double
対応

2021-11-29 13:51 UTC, anatawa12 requested changes
残りのConversationの処理(返信)お願いします

2021-11-29 15:58 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/TileCustomBase.kt
> +        return if (blockType is ModelNormalBlockContainer) {
ModelNormalTileEntity　に移動

2021-11-29 16:01 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/TileCustomBase.kt
> +open class TileCustomBase : TileEntity() {
KotlinUtilに拡張関数で組み込み＆ModelNormalTileEntityで呼び出し。
TileCustomBaseを分解。

2021-11-29 16:02 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatableYaw.kt
> +interface IRotatableYaw {
ReName

2021-11-29 16:02 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +    fun syncAngleSerToCli() {
ReName

2021-11-29 16:02 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modcore/baseclass/module/rotatable/IRotatablePitch.kt
> +interface IRotatablePitch {
ReName

2021-11-29 23:48 UTC, anatawa12 requested changes

2021-11-29 23:48 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +fun TileEntity.getDataSyncPacket(): Packet {
具体的な名前で何するか書いた方がいいかと思います。`newPacketUpdateTileEntity(tileEntity: TileEntity)`
的な形とか。また戻り値もS35PacketUpdateTileEntity型の方がいいかと

2021-11-29 23:48 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +fun TileEntity.onDataSyncPacket(pkt: S35PacketUpdateTileEntity) {
こちらも`S35PacketUpdateTileEntity.loadTo(tileEntity: TileEntity)`みたいな形のものの方がいいと思います

2021-11-30 01:14 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +fun TileEntity.getDataSyncPacket(): Packet {
処置

2021-11-30 01:14 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/KotlinUtil.kt
> +fun TileEntity.onDataSyncPacket(pkt: S35PacketUpdateTileEntity) {
処置

2021-11-30 02:12 UTC, anatawa12 approved these changes
いいと思います

2021-11-30 02:16 UTC, merged