Implemented and used a version of WavefrontObject that supports paral…
freedom-mod-development-community/anti-raid-weapons pull request #6
Opened 2021-12-05 09:54 UTC by KumaYamamoto

…lel processing

2021-12-05 23:53 UTC, anatawa12 requested changes

2021-12-05 23:53 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +package xyz.fmdc.arw.modelloder
本家のcopyright情報を入れましょうと言いたいのですが、arwのライセンスを確定させないと本家との混同されかねないので、そっちを先に別PullReqでやりましょう。

ライセンスを確定した後に追記する文章:
```
This file is originally a part of MinecaftForge.
This file is available under and governed by the <ライセンス名>. 
However, the original source was available under Forge Public License (https://github.com/MinecraftForge/MinecraftForge/blob/9274e4fe435cb415099a8216c1b42235f185443e/MinecraftForge-License.txt)
```

2021-12-05 23:53 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +            while (reader.readLine().also { currentLine = it } != null) {
```
for (currentLine in reader.lineSequence()) {
```
あとこれすると`currentLine!!`が`currentLine`に置き換えられるようになるはず

2021-12-05 23:53 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +    var groupObjects = ArrayList<GroupObject?>()
多分`ArrayList<GroupObject>`がいい。使用箇所全てで`!!`やってるので。

2021-12-05 23:53 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +    private val vertexPattern =
ここらの正規表現、元々はstaticのようなので`companion object`内に移動させてください。

2021-12-05 23:53 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +class WavefrontObject : IModelCustom {
少メモリ化のためにパーサーとオブジェクトを分けるって書いておきたいです。
`TODO: Split parser and parsed object for small memory`

2021-12-06 13:42 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +class WavefrontObject : IModelCustom {
記載

2021-12-06 13:42 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +    private val vertexPattern =
移動

2021-12-06 13:42 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +    var groupObjects = ArrayList<GroupObject?>()
変更

2021-12-06 13:42 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +            while (reader.readLine().also { currentLine = it } != null) {
置き換え＆各所から！！の除去

2021-12-06 15:18 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +package xyz.fmdc.arw.modelloder
追加

2021-12-07 09:20 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +package xyz.fmdc.arw.modelloder
いや、この文言はこのファイルの先頭につけてほしいです

2021-12-07 09:48 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +package xyz.fmdc.arw.modelloder
移動

2021-12-07 13:09 UTC, anatawa12 requested changes

2021-12-07 13:09 UTC, anatawa12 commented on NOTICE
> +* xyz.fmdc.arw.modelloder.WavefrontObject.kt
#8 とのコンフリクトも面倒ですし、これ消してもらっていいですか？

2021-12-07 13:53 UTC, KumaYamamoto commented on NOTICE
> +* xyz.fmdc.arw.modelloder.WavefrontObject.kt
削除

2021-12-07 21:56 UTC, anatawa12 approved these changes

2021-12-07 23:16 UTC, merged