Create COPYING / COPYING.LESSER
freedom-mod-development-community/anti-raid-weapons pull request #8
Opened 2021-12-06 15:06 UTC by KumaYamamoto

2021-12-06 22:44 UTC, anatawa12 requested changes
あと、コピーライト表記の明確化のためにNOTICEって名前で

```
Anti Raid Weapons
Copyright (c) 2021 KumaYamamoto, anatawa12, noyciy7037 and other contributors
```

って追加すると良いかもしれない

2021-12-06 22:44 UTC, anatawa12 commented on build.gradle.kts
> +            exclude("COPYING.txt")
`.txt`はついてないのでこれだとライセンスコピーされないです

2021-12-07 01:13 UTC, KumaYamamoto commented on build.gradle.kts
> +            exclude("COPYING.txt")
あ”。修正

2021-12-07 09:19 UTC, anatawa12 requested changes

2021-12-07 09:19 UTC, anatawa12 commented on build.gradle.kts
> +            exclude("COPYING.LESSER")
多分Noticeも追加したほうがいい

2021-12-07 09:46 UTC, KumaYamamoto commented on build.gradle.kts
> +            exclude("COPYING.LESSER")
追加

2021-12-07 13:08 UTC, anatawa12 commented on build.gradle.kts
> +            exclude("Notice")
大文字小文字は揃えましょう。環境によっては正しく動かないです。

2021-12-07 13:37 UTC, KumaYamamoto commented on build.gradle.kts
> +            exclude("Notice")
あれ？大文字に揃ってなかった。修正

2021-12-07 21:54 UTC, anatawa12 approved these changes

2021-12-07 23:15 UTC, merged