Implement CIC and rendering glowing block
freedom-mod-development-community/anti-raid-weapons pull request #9
Opened 2021-12-08 00:54 UTC by KumaYamamoto

2021-12-08 04:30 UTC, anatawa12 requested changes

2021-12-08 04:30 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun bindTexture(tile: T) {
KotlinUtilがいいと思います

2021-12-08 04:30 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun renderBase(tile: IGlowingModel) {
renderBaseWithGlowingってして、引数をlight値にするといいかと思います

2021-12-08 04:30 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +}
New line at the end of file.

2021-12-08 05:01 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun bindTexture(tile: T) {
電源のON/OFFとかによって使うテクスチャを切り替えたりするためにoverrideするのを想定しております。

2021-12-08 05:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun renderBase(tile: IGlowingModel) {
変更

2021-12-08 05:25 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/modelloder/WavefrontObject.kt
> +}
追加

2021-12-08 06:29 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun bindTexture(tile: T) {
それなら、bindTextureじゃなくて、getTexture()のほうが良いか。

2021-12-08 06:32 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun bindTexture(tile: T) {
変更

2021-12-08 12:22 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun getTexture(tile: T): ResourceLocation {
この関数の存在理由は何ですか？

2021-12-08 12:37 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun getTexture(tile: T): ResourceLocation {
電源のON/OFFとかによって使うテクスチャを切り替えたりするためにoverrideするのを想定しております。

2021-12-08 22:22 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun getTexture(tile: T): ResourceLocation {
であればtexture(abstract val)をこのクラスからは消してこの関数をabstractにするのがいいと思います。
必要であればtextureをabstractで定義したクラスを作ってもいいかもしれない。

2021-12-09 10:48 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun getTexture(tile: T): ResourceLocation {
殆どの設置物はテクスチャが変化しないから必要かな。〇〇fixTextureとでも付けておこう。

2021-12-09 11:45 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBase.kt
> +    open fun getTexture(tile: T): ResourceLocation {
処置

2021-12-09 15:50 UTC, anatawa12 requested changes

2021-12-09 15:50 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBaseFixTexture.kt
> +abstract class ModelNormalModelBaseFixTexture<T : TileEntity> : ModelNormalModelBase<T>() {
テクスチャが固定という意味でしたらFixedTextureにしましょう

2021-12-09 15:50 UTC, anatawa12 commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalRotatableModelBaseFixTexture.kt
> +}
new line. IDEの設定で保存時に追加する設定あったと思うので追加を推奨します

2021-12-10 11:38 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalModelBaseFixTexture.kt
> +abstract class ModelNormalModelBaseFixTexture<T : TileEntity> : ModelNormalModelBase<T>() {
Rename

2021-12-10 11:38 UTC, KumaYamamoto commented on src/main/java/xyz/fmdc/arw/baseclass/modelblock/ModelNormalRotatableModelBaseFixTexture.kt
> +}
設定見つけました。
Add newline at the end of file.

2021-12-10 16:01 UTC, anatawa12 approved these changes
OK. 変更するたびにDiscussionにコメントしないでも問題ないです。RequestReviewは単体でメールくるので。

2021-12-10 16:02 UTC, merged